### ISSUE TITLE
Data in “Show Total Cash Held” and “Press to Collect Cash” fields not reset to null when the user successfully pushes “Press Here When Finished”

### ISSUE THREAD

**Issue by tsriraj** [neelamkpatil/VMCS#2]
Issue: Data in “Show Total Cash Held” and “Press to Collect Cash” fields not reset to null when the user successfully pushes “Press Here When Finished”.

Expected Result: On completion of session, the data in “Show Total Cash Held” and “Press to Collect Cash” fields in the screen should be reset to null
![def01](https://user-images.githubusercontent.com/25021063/44775564-817b5880-aba8-11e8-84fd-2532c136f4f6.png)

**Comment by neelamkpatil** [comment]
We will recreate the issue in dev environment and try to fix it. 
Assigning issue to @xiaoai0109

**Comment by xiaoai0109** [comment]
Defect fixed and committed to repository master branch. 
Commit version: cb2f7f4
Changed file: sg.edu.nus.iss.vmcs.maintenance.MaintenanceController.java

Assigning issue to @tsriraj to test.

**Comment by tsriraj** [comment]
Retested and defect is working fine i.e Data of the previous session are reset to null.
Regression test cases related to Maintenance Panel have been successfully tested and working fine.
![def01_workingscreenshot](https://user-images.githubusercontent.com/25021063/44779752-e3d95680-abb2-11e8-96a5-74920918f220.png)
