### ISSUE TITLE
Change request: Provide an at a glance display of cash amount available, by denomination, for collection by the Maintainer.

### ISSUE THREAD

**Issue by surbhitayal1992** [neelamkpatil/VMCS#3]
The system is required to provide an at-a-glance display of the cash amount available, by denomination, for collection by the Maintainer. This will enable the Maintainer to readily tally the total cash collected and the total number of coins by denomination displayed in “Show Total Cash Held” and “Press to Collect Cash” when pressed, thus leaving no room for dispute over system errors. 

Expected Result: The denomination quantity and amount tally with the Total Cash Held and Total Coins to Collect.

**Comment by neelamkpatil** [comment]
Assigning enhancement request to @weixianghong  for analyzing impact on work-products

**Comment by neelamkpatil** [comment]
Assigning change request to @xiaoai0109  to work on it.

**Comment by xiaoai0109** [comment]
Committed changes in branch 'branch_R1.0.9_en'. 
Changed files: CoinDisplay.java, CoinLabelItem.java, CoinLabelItemDisplay.java, MaintenanceController.java, MaintenancePanel.java, StoreController.java, TotalCashButtonListener.java
Commit version: 89726c8

Assigning @neelamkpatil to review.

**Comment by neelamkpatil** [comment]
Reviewed changes in all 7 files. Approving the changes. Assigning it to QA for testing @tsriraj

**Comment by tsriraj** [comment]
All the scenarios related to denomination quantity and amount tally with total cash held and total coins to collect have been successfully tested and results looks good.
Regression scenarios related to maintenance panel have also been tested and no issues were observed.
![cr01_workingscreenshot-1](https://user-images.githubusercontent.com/25021063/45077764-9b74e800-b120-11e8-8754-f326925f694a.png)
![cr01_workingscreenshot-2](https://user-images.githubusercontent.com/25021063/45077769-9fa10580-b120-11e8-90c5-7f481f55d8c5.png)
